apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: hms-pro
  labels:
    app: grafana
spec:
  ports:
    - port: 3001
      targetPort: 3000
      name: http
  selector:
    app: grafana
  type: ClusterIP
