apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-config
  namespace: hms-pro
data:
  prometheus-datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-svc.hms-pro.svc.cluster.local:9090
        isDefault: true
        editable: true

  dashboards-provider.yml: |
    apiVersion: 1
    providers:
      - name: 'HMS-PRO Dashboards'
        orgId: 1
        folder: 'HMS-PRO'
        type: file
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 10
        options:
          path: /etc/grafana/dashboards
