apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: hms-pro
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'gateway-ms'
        metrics_path: '/q/metrics'
        static_configs:
          - targets: ['gateway-ms-svc.hms-pro.svc.cluster.local:9000']
            labels:
              service: 'gateway-ms'

      - job_name: 'user-ms'
        metrics_path: '/q/metrics'
        static_configs:
          - targets: ['user-ms-svc.hms-pro.svc.cluster.local:8080']
            labels:
              service: 'user-ms'

      - job_name: 'profile-ms'
        metrics_path: '/q/metrics'
        static_configs:
          - targets: ['profile-ms-svc.hms-pro.svc.cluster.local:9100']
            labels:
              service: 'profile-ms'

      - job_name: 'appointment-ms'
        metrics_path: '/q/metrics'
        static_configs:
          - targets: ['appointment-ms-svc.hms-pro.svc.cluster.local:9200']
            labels:
              service: 'appointment-ms'

      - job_name: 'pharmacy-ms'
        metrics_path: '/q/metrics'
        static_configs:
          - targets: ['pharmacy-ms-svc.hms-pro.svc.cluster.local:9300']
            labels:
              service: 'pharmacy-ms'

      - job_name: 'payment-ms'
        metrics_path: '/q/metrics'
        static_configs:
          - targets: ['payment-ms-svc.hms-pro.svc.cluster.local:8086']
            labels:
              service: 'payment-ms'

      - job_name: 'notification-ms'
        metrics_path: '/q/metrics'
        static_configs:
          - targets: ['notification-ms-svc.hms-pro.svc.cluster.local:8085']
            labels:
              service: 'notification-ms'
