quarkus.application.name=PaymentMS
quarkus.http.port=8086

# Database Configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=TaM123456789@
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/paymentdb?createDatabaseIfNotExist=true
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Kafka Configuration (SmallRye Reactive Messaging)
kafka.bootstrap.servers=localhost:29092

# Outgoing channel for Payment Success Events
mp.messaging.outgoing.payment-success-out.connector=smallrye-kafka
mp.messaging.outgoing.payment-success-out.topic=payment_success_topic
mp.messaging.outgoing.payment-success-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# MoMo Sandbox Configuration
momo.partner-code=MOMO
momo.access-key=F8BBA842ECF85
momo.secret-key=K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo-api/mp-rest/url=https://test-payment.momo.vn/v2/gateway/api
momo.ipn-url=https://unoccluded-unjustly-briella.ngrok-free.dev/payment/ipn-callback
momo.redirect-url=http://localhost:3000/admin/payment-result

# CORS
# CORS (Disabled because Gateway handles it)
quarkus.http.cors=false
