apiVersion: v1
kind: ConfigMap
metadata:
  name: hms-config
  namespace: hms-pro
data:
  # Microservices URLs (K8s Service DNS)
  USERMS_URL: "http://user-ms-svc:8080"
  PROFILEMS_URL: "http://profile-ms-svc:9100"
  APPOINTMENTMS_URL: "http://appointment-ms-svc:9200"
  PHARMACYMS_URL: "http://pharmacy-ms-svc:9300"
  PAYMENTMS_URL: "http://payment-ms-svc:8086"
  MEDIAMS_URL: "http://media-ms-svc:9400"
  
  # Cache & Messaging hosts
  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-svc:9092"
  
  # Database URLs (pointing to K8s MySQL StatefulSet svc)
  USER_DB_URL: "jdbc:mysql://mysql-svc:3306/userdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
  PROFILE_DB_URL: "jdbc:mysql://mysql-svc:3306/profiledb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
  APPOINTMENT_DB_URL: "jdbc:mysql://mysql-svc:3306/appointmentdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
  PHARMACY_DB_URL: "jdbc:mysql://mysql-svc:3306/pharmacydb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
  PAYMENT_DB_URL: "jdbc:mysql://mysql-svc:3306/paymentdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
  MEDIA_DB_URL: "jdbc:mysql://mysql-svc:3306/mediadb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
  
  # DB Username
  DB_USERNAME: "root"

  # CORS Configurations (pointing to local ingress domain)
  CORS_ALLOWED_ORIGINS: "*"
  ALLOWED_ORIGINS: "*"
