apiVersion: v1
kind: Secret
metadata:
  name: hms-secret
  namespace: hms-pro
type: Opaque
data:
  # Base64 encoded values
  DB_PASSWORD: "VGFNMTIzNDU2Nzg5QA=="     # TaM123456789@
  HMS_SECRET_KEY: "U0VDUkVU"              # SECRET
