quarkus.application.name=ProfileMS
quarkus.http.port=9100

# Database
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${DB_URL:jdbc:mysql://localhost:3306/profiledb?createDatabaseIfNotExist=true}
quarkus.datasource.username=${DB_USERNAME:root}
quarkus.datasource.password=${DB_PASSWORD:TaM123456789@}

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Redis
quarkus.redis.hosts=redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}

# CORS (Disabled because Gateway handles it)
quarkus.http.cors=false
