{
 "title": "HTTP Metrics",
 "tags": [
  "hms-pro",
  "http"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service=~\"$service\"}[5m])) by (service, status)",
     "legendFormat": "{{service}} [{{status}}]"
    }
   ]
  },
  {
   "title": "HTTP Request Latency (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{service=~\"$service\"}[5m])) by (le, service))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "HTTP 5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\", service=~\"$service\"}[5m])) by (service)",
     "legendFormat": "{{service}} - 5xx Errors"
    }
   ]
  },
  {
   "title": "HTTP Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=~\"$service\"}[5m])) by (service) / sum(rate(http_server_requests_seconds_count{service=~\"$service\"}[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}