{
 "title": "JVM Overview",
 "tags": [
  "hms-pro",
  "jvm"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JVM Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", service=~\"$service\"}",
     "legendFormat": "{{service}} - Used"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\", service=~\"$service\"}",
     "legendFormat": "{{service}} - Max"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_usage{service=~\"$service\"} * 100",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "JVM Threads Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{service=~\"$service\"}",
     "legendFormat": "{{service}} - Live"
    },
    {
     "expr": "jvm_threads_daemon_threads{service=~\"$service\"}",
     "legendFormat": "{{service}} - Daemon"
    }
   ]
  },
  {
   "title": "Garbage Collection Pause Rate (per sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{service=~\"$service\"}[5m])",
     "legendFormat": "{{service}} - GC pause sum"
    }
   ]
  }
 ]
}