quarkus.application.name=AppointmentMS
quarkus.http.port=9200

# Database
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${DB_URL:jdbc:mysql://localhost:3306/appointmentdb?createDatabaseIfNotExist=true}
quarkus.datasource.username=${DB_USERNAME:root}
quarkus.datasource.password=${DB_PASSWORD:TaM123456789@}

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# REST Clients
quarkus.rest-client."profile-api".url=${PROFILEMS_URL:http://localhost:9100}

# Kafka Messaging (SmallRye Reactive Messaging)
mp.messaging.outgoing.notification-appointment.connector=smallrye-kafka
mp.messaging.outgoing.notification-appointment.topic=notification-appointment
mp.messaging.outgoing.notification-appointment.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Kafka Common
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

# CORS (Disabled because Gateway handles it)
quarkus.http.cors=false

# Caching (Redis)
quarkus.cache.type=redis
quarkus.redis.hosts=redis://localhost:6379

# Cache Value Types (Required for Redis)
quarkus.cache.redis.stats-dashboard.value-type=java.util.List
quarkus.cache.redis.stats-reasons.value-type=java.util.List