quarkus.application.name=UserMS
quarkus.http.port=8080

# Database
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${DB_URL:jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true}
quarkus.datasource.username=${DB_USERNAME:root}
quarkus.datasource.password=${DB_PASSWORD:TaM123456789@}

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Custom properties (kept for migration compatibility)
# ProfileMS REST Client
quarkus.rest-client."profile-api".url=${PROFILEMS_URL:http://localhost:9100}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

# CORS (Disabled because Gateway handles it)
quarkus.http.cors=false

# JWT configuration (if using SmallRye JWT for automatic verification)

# quarkus.smallrye.jwt.verify-key.location=publickey.pem