CREATE DATABASE IF NOT EXISTS userdb;
CREATE DATABASE IF NOT EXISTS profiledb;
CREATE DATABASE IF NOT EXISTS appointmentdb;
CREATE DATABASE IF NOT EXISTS pharmacydb;
CREATE DATABASE IF NOT EXISTS paymentdb;
CREATE DATABASE IF NOT EXISTS mediadb;
