quarkus.application.name=media
quarkus.http.port=9400

# Database Configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=${DB_USERNAME:root}
quarkus.datasource.password=${DB_PASSWORD:TaM123456789@}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:mysql://localhost:3306/mediadb?createDatabaseIfNotExist=true}
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Multipart configuration
quarkus.http.limits.max-body-size=10M

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}