apiVersion: v1
kind: Service
metadata:
  name: appointment-ms-svc
  namespace: hms-pro
  labels:
    app: appointment-ms
spec:
  ports:
    - port: 9200
      targetPort: 9200
      name: http
  selector:
    app: appointment-ms
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-ms
  namespace: hms-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-ms
  template:
    metadata:
      labels:
        app: appointment-ms
    spec:
      containers:
        - name: appointment-ms
          image: hms/appointment-ms:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9200
              name: http
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: APPOINTMENT_DB_URL
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hms-secret
                  key: DB_PASSWORD
            - name: PROFILEMS_URL
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: PROFILEMS_URL
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: REDIS_PORT
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: HMS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: hms-secret
                  key: HMS_SECRET_KEY
            - name: JAVA_OPTS
              value: "-Xms64m -Xmx200m -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
          resources:
            limits:
              cpu: "500m"
              memory: "300Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 8
          readinessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 8
