apiVersion: v1
kind: Service
metadata:
  name: gateway-ms-svc
  namespace: hms-pro
  labels:
    app: gateway-ms
spec:
  ports:
    - port: 9000
      targetPort: 9000
      name: http
  selector:
    app: gateway-ms
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-ms
  namespace: hms-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-ms
  template:
    metadata:
      labels:
        app: gateway-ms
    spec:
      containers:
        - name: gateway-ms
          image: hms/gateway-ms:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              name: http
          env:
            - name: USERMS_URL
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: USERMS_URL
            - name: PROFILEMS_URL
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: PROFILEMS_URL
            - name: APPOINTMENTMS_URL
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: APPOINTMENTMS_URL
            - name: PHARMACYMS_URL
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: PHARMACYMS_URL
            - name: MEDIAMS_URL
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: MEDIAMS_URL
            - name: PAYMENTMS_URL
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: PAYMENTMS_URL
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: ALLOWED_ORIGINS
            - name: JAVA_OPTS
              value: "-Xms64m -Xmx200m -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
          resources:
            limits:
              cpu: "500m"
              memory: "300Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 8
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 8
