apiVersion: v1
kind: Service
metadata:
  name: hms-fe-svc
  namespace: hms-pro
  labels:
    app: hms-fe
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: hms-fe
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hms-fe
  namespace: hms-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-fe
  template:
    metadata:
      labels:
        app: hms-fe
    spec:
      containers:
        - name: hms-fe
          image: hms/hms-fe:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
