apiVersion: v1
kind: Service
metadata:
  name: media-ms-svc
  namespace: hms-pro
  labels:
    app: media-ms
spec:
  ports:
    - port: 9400
      targetPort: 9400
      name: http
  selector:
    app: media-ms
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-ms
  namespace: hms-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-ms
  template:
    metadata:
      labels:
        app: media-ms
    spec:
      containers:
        - name: media-ms
          image: hms/media-ms:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9400
              name: http
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: MEDIA_DB_URL
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hms-secret
                  key: DB_PASSWORD
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: CORS_ALLOWED_ORIGINS
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: REDIS_PORT
            - name: JAVA_OPTS
              value: "-Xms64m -Xmx200m -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
          resources:
            limits:
              cpu: "500m"
              memory: "300Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            tcpSocket:
              port: 9400
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 8
          readinessProbe:
            tcpSocket:
              port: 9400
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 8
