apiVersion: v1
kind: Service
metadata:
  name: notification-ms-svc
  namespace: hms-pro
  labels:
    app: notification-ms
spec:
  ports:
    - port: 8085
      targetPort: 8085
      name: http
  selector:
    app: notification-ms
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-ms
  namespace: hms-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-ms
  template:
    metadata:
      labels:
        app: notification-ms
    spec:
      containers:
        - name: notification-ms
          image: hms/notification-ms:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
              name: http
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: hms-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: JAVA_OPTS
              value: "-Xms64m -Xmx200m -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
          resources:
            limits:
              cpu: "500m"
              memory: "300Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"

