quarkus.http.port=9300
quarkus.application.name=PharmacyMS
quarkus.kafka.devservices.enabled=false

# Datasource
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${DB_URL:jdbc:mysql://localhost:3306/pharmacydb?createDatabaseIfNotExist=true}
quarkus.datasource.username=${DB_USERNAME:root}
quarkus.datasource.password=${DB_PASSWORD:TaM123456789@}

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Redis
quarkus.redis.hosts=redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}

# Kafka
mp.messaging.incoming.payment-success.connector=smallrye-kafka
mp.messaging.incoming.payment-success.topic=payment_success_topic
mp.messaging.incoming.payment-success.auto.offset.reset=earliest
mp.messaging.incoming.payment-success.value.deserializer=com.hms.PharmacyMS.config.PaymentSuccessEventDeserializer
mp.messaging.incoming.payment-success.group.id=PharmacyMS-Group
kafka.bootstrap.servers=localhost:29092

# Rest Client
payment-api/mp-rest/url=${PAYMENTMS_URL:http://localhost:9094}

# Security & CORS
hms.secret-key=${HMS_SECRET_KEY:SECRET}
# CORS (Disabled because Gateway handles it)
quarkus.http.cors=false

# MoMo Config (used in SaleAPI via PaymentClient indirectly or directly if needed)
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.partnerCode=MOMO
momo.accessKey=F8BBA842ECF85
momo.secretKey=K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.ipnUrl=https://unoccluded-unjustly-briella.ngrok-free.dev/pharmacy/payment/ipn
momo.returnUrl=https://unoccluded-unjustly-briella.ngrok-free.dev/payment-success

# Connection pool optimization
quarkus.datasource.jdbc.idle-removal-interval=5m
quarkus.datasource.jdbc.max-lifetime=10m