quarkus.application.name=NotificationMS
quarkus.http.port=8085

# Kafka Configuration (SmallRye Reactive Messaging)
kafka.bootstrap.servers=localhost:29092

# Incoming channel for Appointment Events
mp.messaging.incoming.appointment-in.connector=smallrye-kafka
mp.messaging.incoming.appointment-in.topic=notification-appointment
mp.messaging.incoming.appointment-in.group.id=notification-group-v2
mp.messaging.incoming.appointment-in.auto.offset.reset=earliest
mp.messaging.incoming.appointment-in.value.deserializer=com.hms.NotificationMS.config.AppointmentEventDeserializer

# Mail Configuration (Gmail)
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.username=tamdao1742005@gmail.com
quarkus.mailer.password=gfek khap yrvw zyqp
quarkus.mailer.starttls=REQUIRED
quarkus.mailer.auth-mechanisms=LOGIN,PLAIN
